language: java
dist: trusty
deploy:
  provider: releases
  api_key:
    secure: fIxU6tQLYnY1BuzTk6GCEmuqtkPIvwoOMnWx/k0WB6nT9k1vnesnuEG9DKnNbiqGc5PeYabWn/l7Br4V07sAlU6sI9M86Cak50HNVzTILezKXL7CLgj7N92ti+piBG2g8WMNXwEgUZeCvTvJtsAe8BrI3U84TM0mXNmfjAHuDdgokVrXLm4Kn9TPAN0Qw8P0Tg9GNzuHCKdEZAM0x7vHD5gipEi7RCvoyv4dbmaxo06oIKhqSqG5FE47cFwRLY1Yd9hKhtA4pcPE0OGAd77/WPERBKvC4sj4B/Y/pXTZknLz7D+R6QeHchSdUyd4/X+z97wEQYwbRTgI5DnFhiuYI4xZvn0vlOdV+pLOe1OUrn+05Jexy9lvNCM4Vysh9N08YxE4BIPqcCZpWtG20UWQPnu/fJz9nLCe/1j12kEm20X/+7iOotCrI53y1hLS+TBlPL14zKOF1nX1e8585/lJOu2WzgvAFwKZoPrt/bSTfB4QL5kQfj5AsICofh76bUmb6PRc9DK3g5wOxGZUvNFxO2tvCNBj0MD3ZCmG/gbvq6Znz4zUgg4O9w0IMUW7ObTevfFFseNFepcP7SgqNUlYZOdKajfNjW6zNnmpFG4hlvnNPYmpIl9hCJ5hYiy9INAWenlVAmsaRoD8jvc71bJNzuLPJPArqjm7eCM6s8rf5Jk=
  file-glob: true
  file: 'target/HatMeEnhanced-*.jar'
  on:
    repo: egg82/HatMeEnhanced
addons:
  sonarcloud:
    organization: 'egg82-github'
    token:
      secure: "gnD78pbDzYObktEnq3hKf96lstQzVwhDQbZDQ1dSJ/KDTBc4dteOmlobxQasK9FM1iEt3Q2JrhEBqPDMh+F61q6XadAf9hFlFmo9uHA/m8DfSr5TJ8bp1oJ/Nk4civwG1n2Mpr6+OUBDh3OvFNZciq6KgQ1Jmtx/dyHPqFu/wMX2P0ZYFcO8LmV/iWybZPMAHosaA0s2NQ+X08JP4cXro0vDNAZ6SE4YK9FgLbUZg8RY7COjZ1xtu4DRF7o2aYF/AHhqndSaiEKujaelsep0EmPdWCbFlX0NzumjsiMjRy2c8JIEyhA9524ptO+wCMkQU36y69LsgBbSHMeo9mzrwN6QzuvY9KA07WXIaXrJJpY73T/se3pHQp0RP347oXh+bOWF6Z5HXP+zBnyHt6k/WjVuLxB2yMiko8OQ3enAv1mkkFMVqLEZ+G6yxHP5i0So+jHj75EgI5cBJbJbuWTbocDkWdYakSPfcLm0sikFS5ge1swolrAINdUXnrlvgNPtZQVMIIzAeMq3+9tVsQ3oyu6zpb8Ad8vAbSyLjh3jwlQeEss41oJw+3Zfckd1bogpRy/WW90xlxxEV7m+wvEbYKVoSMFMyG//6MR5IkVUGw71CmSliRLCqIpcHVrQ5yY1JomOxWaqIlwKpdIhkdNtrKRucoQn1CNFzda8Fi4QI3E="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar