name: HatMeEnhanced
main: me.egg82.hme.HatMeEnhanced
version: 2.0.6
softdepend: [LightAPI]
commands:
  hat:
    description: Puts the item (or item stack with -a) in your hand on your head. Optionally uses an item ID or type instead. 
    usage: /hat [-a,itemID]
  unhat:
    description: Puts the item in your head in your inventory.
    usage: /unhat